#!/usr/bin/env python3
from __future__ import annotations

import argparse

from app.db import init_db
from app.ingestion.legistar_ingest import run_legistar_ingest


def main() -> None:
    parser = argparse.ArgumentParser(prog='cw')
    sub = parser.add_subparsers(dest='command', required=True)
    ingest = sub.add_parser('ingest')
    ingest.add_argument('--source', default='whatcom_legistar_api')
    ingest.add_argument('--all', action='store_true')
    ingest.add_argument('--mode', choices=['backfill', 'incremental'], default='incremental')
    ingest.add_argument('--from', dest='from_date')
    ingest.add_argument('--to', dest='to_date')

    args = parser.parse_args()
    if args.command == 'ingest':
        init_db()
        source = 'all' if args.all else args.source
        result = run_legistar_ingest(mode=args.mode, source=source, from_date=args.from_date, to_date=args.to_date)
        print(result)


if __name__ == '__main__':
    main()
